os:
  - osx

matrix:
  include:
    dotnet: 1.0.0-preview2-003131
    mono: none
    env: DOTNETCORE=1

before_install:
 - sudo gem install bundler
 - sudo bundle install

script:
 - rake test

notifications:
  email: false
